name: CD
on:
  push:
    branches: [main]
jobs:
  build:
    name: Build
    runs-on: ubuntu-latest
    steps:
      - name: checkout
        uses: actions/checkout@v2

      - name: build image and push to docker hub
        uses: docker/build-push-action@v1.1.0
        with:
          username: wilsonbl
          password: ${{ secrets.DOCKER_PASSWORD }}
          repository: wilsonleandro/argocd-golang
          tags: ${{ github.sha }}, latest

  deploy:
    name: Deploy
    runs-on: ubuntu-latest
    needs: build
    steps:
      - name: checkout
        uses: actions/checkout@v2

      - name: kustomize
        uses: imranismail/setup-kustomize@v1
        with:
          kustomize_version: v3.6.1

      - name: Update K8S
        run: |
          cd k8s
          kustomize edit set image goapp=wilsonbl/argocd-golang:${{ github.sha }}
          cat kustomization.yaml

      - name: Commit
        run: |
          git config --local user.email "action@github.com"
          git config --local user.name "Deploy Action"
          git commit -am "change image tag"

      - name: Push
        uses: ad-m/github-push-action@master
